apiVersion: v1
kind: Pod
metadata:
  name: memory-consumer
spec:
  containers:
  - name: memory-consumer-container
    image: memory_consumer:6.0
    imagePullPolicy: Never
    resources:
      requests:
        memory: "512Mi"
      limits:
        memory: "1Gi"
    env:
    - name: JVM_OPTS
      value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms64M -XshowSettings:vm"
#    env:
#    - name: JVM_OPTS
#      value: "-Xms64M -Xmx256M"
  restartPolicy: Never
